CREATE USER 'ryze'@'*' IDENTIFIED WITH mysql_native_password BY 'pw';

GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'ryze'@'*' WITH GRANT OPTION;

FLUSH PRIVILEGES;